### ISSUE TITLE
material about AER1513

### ISSUE THREAD

**Issue by icameling** [msorocky/AER1513_Project#1]
Hello, I am a master of ZheJiang University, my research direction is laser IMU tight coupling. And I am reading State Estimation for Robotics writen by Barfoot.I am wondering if you have some material about AER1513 . I am  really appreciate if you could send me some material about AER1513 course. My email adress is 1216032111@qq.com. Thanks a lot~~

**Comment by msorocky** [comment]
Hello, the textbook is an expanded version of his lecture notes, so you'd already have access to the content the course covers. The course project is up to the student to determine, the only requirement being that it is related to state estimation. Hope that helps!

**Comment by icameling** [comment]
Thank you for your reply, I will concentrate on reading the textbook.
Thanks again！

**Comment by msorocky** [comment]
You're welcome!
